#!/usr/bin/env python3

import sys
from PySide.QtGui import *
from ImageWindow import *

app = QApplication(sys.argv)
app.setOrganizationName("OpenGear")
app.setApplicationName("WallpaperHelper")

window = ImageWindow()
window.show()

ret = app.exec_()
sys.exit(ret)
