#!/usr/bin/env python3

import sys
try:
	from PySide6.QtGui import *
except Exception:
	try:
		from PySide2.QtGui import *
	except Exception:
		from PySide.QtGui import *
from ImageWindow import *

app = QApplication(sys.argv)
app.setOrganizationName("OpenGear")
app.setApplicationName("WallpaperHelper")

window = ImageWindow()
window.show()

try:
	ret = app.exec()
except Exception:
	ret = app.exec_()
sys.exit(ret)
